name: risk
description: A sample Polymer application
dependencies:
  polymer: any
  bootstrap_for_pub: ">=3.1.0+2 <4.0.0"
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
